#!/usr/bin/env zsh

set -xe
dir="$(dirname $0)"

genkubeconfig() {
  cert=$1
  user=$2

  kubectl config set-cluster kubenet \
    --certificate-authority="$dir/ca.pem" \
    --embed-certs=true \
    --server=https://kubegate.kubenet:6443 \
    --kubeconfig="$dir/${cert}.kubeconfig"

  kubectl config set-credentials $user \
    --client-certificate="$dir/${cert}.pem" \
    --client-key="$dir/${cert}-key.pem" \
    --embed-certs=true \
    --kubeconfig="$dir/${cert}.kubeconfig"

  kubectl config set-context default \
    --cluster=kubenet \
    --user=$user \
    --kubeconfig="$dir/${cert}.kubeconfig"

  kubectl config use-context default \
    --kubeconfig="$dir/${cert}.kubeconfig"
}

for inst in worker{0,1,2}; do
  genkubeconfig $inst system:node:$inst
done

genkubeconfig kube-proxy system:kube-proxy
genkubeconfig kube-controller-manager system:kube-controller-manager
genkubeconfig kube-scheduler system:kube-scheduler
genkubeconfig admin admin

