#!/usr/bin/env zsh

set -xe
dir="$(dirname $0)"

for inst in control{0,1,2}; do
  scp -o UserKnownHostsFile="$dir/$inst/ssh_known_hosts" setupcontrol setupkubeletaccess ubuntu@${inst}:~
done

for inst in worker{0,1,2}; do
  scp -o UserKnownHostsFile="$dir/$inst/ssh_known_hosts" setupworker ubuntu@${inst}:~
done

