#!/usr/bin/env zsh

set -xe
dir="$(dirname $0)"

for i in $(seq 0 2); do
  scp "$dir/setupcontrol" "$dir/setupkubeletaccess" ubuntu@control$i:~
done

for i in $(seq 0 2); do
  scp "$dir/setupworker" ubuntu@worker$i:~
done

