#!/usr/bin/env zsh

set -xe

helm repo add coredns https://coredns.github.io/helm
helm install -n kube-system coredns coredns/coredns --set service.clusterIP=10.32.0.10 --set replicaCount=2

helm repo add nfs-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
helm install -n kube-system nfs-provisioner nfs-provisioner/nfs-subdir-external-provisioner \
  --set nfs.server=192.168.64.1 \
  --set nfs.path=/Users/rjghik/kubenet/nfs-pvs \
  --set storageClass.defaultClass=true

