#!/usr/bin/env zsh

set -xe

dir=$(dirname $0)
source "$dir"/vmparseargs

case $prefix in
  control|gateway)
    mem=1G
    cpus=1
    ;;
  worker)
    mem=8G
    cpus=2
    ;;
esac

qemu-system-aarch64 \
  -machine virt,accel=hvf,highmem=on \
  -drive if=pflash,readonly=on,format=raw,file=/opt/homebrew/Cellar/qemu/8.0.2/share/qemu/edk2-aarch64-code.fd \
  -drive if=pflash,format=raw,file="$dir/$inst/efi-vars.fd" \
  -m $mem \
  -smp $cpus \
  -cpu host \
  -drive file="$dir/$inst/disk.qcow2",format=qcow2,index=0,media=disk \
  -drive file="$dir/$inst/cidata.iso",driver=raw,if=virtio \
  -nic vmnet-shared,start-address=192.168.64.1,end-address=192.168.64.254,subnet-mask=255.255.255.0,mac=52:54:00:00:00:$ipidx \
  -nographic

