#!/usr/bin/env zsh

inst=$1

if [[ ! "$inst" =~ ^(control|gateway|worker)[0-9]+$ ]]; then
  echo "usage: $0 (control|gateway|worker)<idx>"
  exit 1
fi

case "$inst" in
  control*)
    prefix=control
    idx=${inst:7}
    ipidx=$(($idx + 10))
    ;;
  gateway*)
    prefix=gateway
    idx=${inst:7}
    ipidx=$(($idx + 13))
    ;;
  worker*)
    prefix=worker
    idx=${inst:6}
    ipidx=$(($idx + 20))
    ;;
  *)
    echo "bad instance name: $inst"
    exit 1
esac


