#!/usr/bin/env zsh

set -xe

dir=$(dirname $0)
source "$dir/vmparseargs"

# wait until the instance is ready to accept ssh connections
until nc -zG120 $inst 22; do sleep 1; done

# add new entries for this instance to known_hosts
ssh-keyscan $inst 2> /dev/null >> "$dir/$inst/ssh_known_hosts"

