#!/usr/bin/env zsh

set -xe
dir="$(dirname $0)"

for inst in control{0,1,2}; do
  scp -o UserKnownHostsFile="$dir/../$inst/ssh_known_hosts" \
      "$dir/ca.pem" \
      "$dir/ca-key.pem" \
      "$dir/kubernetes-key.pem" \
      "$dir/kubernetes.pem" \
      "$dir/service-account-key.pem" \
      "$dir/service-account.pem" \
      "$dir/admin.kubeconfig" \
      "$dir/kube-controller-manager.kubeconfig" \
      "$dir/kube-scheduler.kubeconfig" \
      "$dir/encryption-config.yaml" \
      ubuntu@${inst}:~
done

for inst in worker{0,1,2}; do
  scp -o UserKnownHostsFile="$dir/../$inst/ssh_known_hosts" \
      "$dir/ca.pem" \
      "$dir/$inst.pem" \
      "$dir/$inst-key.pem" \
      "$dir/${inst}.kubeconfig" \
      "$dir/kube-proxy.kubeconfig" \
      ubuntu@${inst}:~
done

