#!/usr/bin/env zsh

set -xe
dir="$(dirname $0)"

kubectl config set-cluster kubernetes-the-hard-way \
  --certificate-authority="$dir/ca.pem" \
  --embed-certs=true \
  --server=https://kubegate:6443

kubectl config set-credentials admin \
  --client-certificate="$dir/admin.pem" \
  --client-key="$dir/admin-key.pem"

kubectl config set-context kubernetes-the-hard-way \
  --cluster=kubernetes-the-hard-way \
  --user=admin

kubectl config use-context kubernetes-the-hard-way

